# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id_college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_show.College'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_show.Group'),
        ),
    ]
